name: "Podcast Generator"
author: "Sachin Singh"  # Use a colon (:) instead of a space before it
description: "Generates a feed for a podcast from YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"  # The quote should be double quotes, not a mix of single and double
inputs:
  email:
    description: "The Committer's email address"  # Use quotes for the description
    required: true
    default: ${{ github.actor }}@localhost  # Ensure correct casing for `github.actor`
  name:  # Ensure this is indented properly under `inputs`
    description: "The committer's name"  # Use quotes for the description
    required: true
    default: ${{ github.actor }}  # Ensure correct casing for `github.actor`
